name: Build and Deploy a Jekyll Site to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    
permissions:
  contents: read 
  pages: write
  id-token: write 

concurrency:
  group: "pages"
  cancel-in-progress: true 



jobs:
  build:
    name: build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: "3.1"
          # Runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Version info
        run:
            ruby --version
            gem --version
            bundle --version

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Checking Jekyll Configuration
        run: bundle exec jekyll doctor
        
      - name: Build with Jekyll
        # Defaults output to '/_site'
        run: bundle exec jekyll build --baseurl ${{ steps.pages.outputs.base_path }} --profile --trace
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
          # This will automatically upload an artifact from the '/_site' directory
        uses: actions/upload-pages-artifact@v1
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        with:
          path: ./_site/

      - name: Cleaning up
        run: bundle exec jekyll clean

# Deployment job
  deploy:
    name: deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        if: ${{ success() }}